name: Continuous Integration

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: npm ci

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/cache/restore@v4
        id: cache-npm
        with:
          path: ~/.npm
          key: npm-

      - name: Install node_modules
        run: npm ci --ignore-scripts

      - name: Run lint
        run: npm run lint

      - name: Run style lint
        run: npm run lint:style

      - name: Run Prettier check
        run: npm run prettier:check

  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/cache/restore@v4
        id: cache-npm
        with:
          path: ~/.npm
          key: npm-

      - name: Install node_modules
        run: npm ci --ignore-scripts

      - name: Run tests
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [ lint, run-tests ]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: actions/cache/restore@v4
        id: cache-npm
        with:
          path: ~/.npm
          key: npm-

      - name: Install node_modules
        run: npm ci --ignore-scripts

      - name: Build application
        run: npm run build